use std::cmp::Ordering;
use std::io; //imported the i/o module from the standard library

use rand::Rng;
fn main() {
    println!("Guess the number!");

    let secret_number = rand::thread_rng().gen_range(1..=100);

    // println!("The secret number is: {secret_number}");
    println!("Please input your guess.");
    loop {
        let mut guess = String::new(); //creating a mutable variable

        io::stdin() //calling the stdin function to handle USER INPUT
            .read_line(&mut guess) //calling the read_line method, using &mutguess as the argument, & is a reference 
            .expect("Failed to read line"); //handling the result values generated by the read_line method

        let guess: u64 = guess.trim().parse().expect("Please type a number!");

        println!("You guessed: {guess}");

        match guess.cmp(&secret_number) {
            Ordering::Less => println!("small!"),
            Ordering::Greater => println!("big!"),
            Ordering::Equal => println!("You win!"),
        }
    }
}
